# Redirigir todo el tráfico HTTP a HTTPS
server {
  listen 80;
  server_name 3dcostmanager.com www.3dcostmanager.com;
  return 301 https://$host$request_uri;
}

# Servidor principal en HTTPS
server {
  listen 443 ssl;
  server_name 3dcostmanager.com www.3dcostmanager.com;

  # Rutas a los certificados SSL
  ssl_certificate /etc/letsencrypt/live/3dcostmanager.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/3dcostmanager.com/privkey.pem;
  
  # 1. Frontend Angular
  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    # Si la ruta no existe como archivo, redirige al index para que Angular maneje el router
    try_files $uri $uri/ /index.html;
  }

  # 2. Backend API (Reverse Proxy)
  location /api/ {
    proxy_pass http://api:4000/api/;
    proxy_set_header Host $host;
    proxy_set_header X-Real_IP $remote_addr;
  }
}