server {
  listen 80;
  server_name localhost;
  root /usr/share/nginx/html;

  # Le decimos a Nginx que nuestro archivo principal se llama index.csr.html
  index index.csr.html index.html;

  location / {
    # Si la ruta no existe como archivo, redirige al index para que Angular maneje el router
    try_files $uri $uri/ /index.csr.html;
  }
}